[package]
name = "string-interner"
version = "0.5.0"
authors = ["Robbepop"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/robbepop/string-interner"
documentation = "https://docs.rs/string-interner"
keywords = ["interner", "intern", "string", "str", "symbol"]
description = """A string interning data structure that was designed for minimal memory-overhead
and fast access to the underlying interned string contents.
"""
categories = ["data-structures"]

[dependencies]

[features]
bench = []

[badges]
travis-ci = { repository = "Robbepop/string-interner" }
appveyor = { repository = "Robbepop/string-interner", branch = "master", service = "github" }
