[package]
name = "string-interner"
version = "0.2.0"
authors = ["Robbepop"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/robbepop/string-interner"
documentation = "https://docs.rs/string-interner"
keywords = ["interner", "intern", "string", "str", "symbol"]
description = """A string interning data structure that was designed for minimal memory-overhead
and fast access to the underlying interned string contents. Uses nightly only feature `conservative_impl_trait`!
"""
categories = ["data-structures", "caching", "compression"]

[dependencies]
num-traits = "0.1"
